// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package proto.message;

public final class message {
  private message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface URLObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.URLObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 m_id = 1;</code>
     */
    boolean hasMId();
    /**
     * <code>required int32 m_id = 1;</code>
     */
    int getMId();

    /**
     * <code>required string m_link = 2;</code>
     */
    boolean hasMLink();
    /**
     * <code>required string m_link = 2;</code>
     */
    java.lang.String getMLink();
    /**
     * <code>required string m_link = 2;</code>
     */
    com.google.protobuf.ByteString
        getMLinkBytes();

    /**
     * <code>required string m_domain = 3;</code>
     */
    boolean hasMDomain();
    /**
     * <code>required string m_domain = 3;</code>
     */
    java.lang.String getMDomain();
    /**
     * <code>required string m_domain = 3;</code>
     */
    com.google.protobuf.ByteString
        getMDomainBytes();

    /**
     * <code>required bool m_absolute = 4;</code>
     */
    boolean hasMAbsolute();
    /**
     * <code>required bool m_absolute = 4;</code>
     */
    boolean getMAbsolute();

    /**
     * <code>required int32 m_priority = 5;</code>
     */
    boolean hasMPriority();
    /**
     * <code>required int32 m_priority = 5;</code>
     */
    int getMPriority();

    /**
     * <code>required int64 m_extractedTime = 6;</code>
     */
    boolean hasMExtractedTime();
    /**
     * <code>required int64 m_extractedTime = 6;</code>
     */
    long getMExtractedTime();

    /**
     * <code>required int64 m_crawledTime = 7;</code>
     */
    boolean hasMCrawledTime();
    /**
     * <code>required int64 m_crawledTime = 7;</code>
     */
    long getMCrawledTime();

    /**
     * <code>required int64 m_downloadDuration = 8;</code>
     */
    boolean hasMDownloadDuration();
    /**
     * <code>required int64 m_downloadDuration = 8;</code>
     */
    long getMDownloadDuration();

    /**
     * <code>required int32 m_httpStatusCode = 9;</code>
     */
    boolean hasMHttpStatusCode();
    /**
     * <code>required int32 m_httpStatusCode = 9;</code>
     */
    int getMHttpStatusCode();

    /**
     * <code>required int64 m_relevance = 10;</code>
     */
    boolean hasMRelevance();
    /**
     * <code>required int64 m_relevance = 10;</code>
     */
    long getMRelevance();

    /**
     * <code>required int64 m_distanceFromRelevantPage = 11;</code>
     */
    boolean hasMDistanceFromRelevantPage();
    /**
     * <code>required int64 m_distanceFromRelevantPage = 11;</code>
     */
    long getMDistanceFromRelevantPage();

    /**
     * <code>required int32 m_freshness = 12;</code>
     */
    boolean hasMFreshness();
    /**
     * <code>required int32 m_freshness = 12;</code>
     */
    int getMFreshness();
  }
  /**
   * Protobuf type {@code message.URLObject}
   */
  public static final class URLObject extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:message.URLObject)
      URLObjectOrBuilder {
    // Use URLObject.newBuilder() to construct.
    private URLObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private URLObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final URLObject defaultInstance;
    public static URLObject getDefaultInstance() {
      return defaultInstance;
    }

    public URLObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private URLObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              mId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              mLink_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              mDomain_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              mAbsolute_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              mPriority_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              mExtractedTime_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              mCrawledTime_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              mDownloadDuration_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              mHttpStatusCode_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              mRelevance_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              mDistanceFromRelevantPage_ = input.readInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              mFreshness_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.message.message.internal_static_message_URLObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.message.message.internal_static_message_URLObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.message.message.URLObject.class, proto.message.message.URLObject.Builder.class);
    }

    public static com.google.protobuf.Parser<URLObject> PARSER =
        new com.google.protobuf.AbstractParser<URLObject>() {
      public URLObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new URLObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<URLObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int M_ID_FIELD_NUMBER = 1;
    private int mId_;
    /**
     * <code>required int32 m_id = 1;</code>
     */
    public boolean hasMId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 m_id = 1;</code>
     */
    public int getMId() {
      return mId_;
    }

    public static final int M_LINK_FIELD_NUMBER = 2;
    private java.lang.Object mLink_;
    /**
     * <code>required string m_link = 2;</code>
     */
    public boolean hasMLink() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string m_link = 2;</code>
     */
    public java.lang.String getMLink() {
      java.lang.Object ref = mLink_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mLink_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string m_link = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMLinkBytes() {
      java.lang.Object ref = mLink_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int M_DOMAIN_FIELD_NUMBER = 3;
    private java.lang.Object mDomain_;
    /**
     * <code>required string m_domain = 3;</code>
     */
    public boolean hasMDomain() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string m_domain = 3;</code>
     */
    public java.lang.String getMDomain() {
      java.lang.Object ref = mDomain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mDomain_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string m_domain = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMDomainBytes() {
      java.lang.Object ref = mDomain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mDomain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int M_ABSOLUTE_FIELD_NUMBER = 4;
    private boolean mAbsolute_;
    /**
     * <code>required bool m_absolute = 4;</code>
     */
    public boolean hasMAbsolute() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool m_absolute = 4;</code>
     */
    public boolean getMAbsolute() {
      return mAbsolute_;
    }

    public static final int M_PRIORITY_FIELD_NUMBER = 5;
    private int mPriority_;
    /**
     * <code>required int32 m_priority = 5;</code>
     */
    public boolean hasMPriority() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 m_priority = 5;</code>
     */
    public int getMPriority() {
      return mPriority_;
    }

    public static final int M_EXTRACTEDTIME_FIELD_NUMBER = 6;
    private long mExtractedTime_;
    /**
     * <code>required int64 m_extractedTime = 6;</code>
     */
    public boolean hasMExtractedTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 m_extractedTime = 6;</code>
     */
    public long getMExtractedTime() {
      return mExtractedTime_;
    }

    public static final int M_CRAWLEDTIME_FIELD_NUMBER = 7;
    private long mCrawledTime_;
    /**
     * <code>required int64 m_crawledTime = 7;</code>
     */
    public boolean hasMCrawledTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int64 m_crawledTime = 7;</code>
     */
    public long getMCrawledTime() {
      return mCrawledTime_;
    }

    public static final int M_DOWNLOADDURATION_FIELD_NUMBER = 8;
    private long mDownloadDuration_;
    /**
     * <code>required int64 m_downloadDuration = 8;</code>
     */
    public boolean hasMDownloadDuration() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int64 m_downloadDuration = 8;</code>
     */
    public long getMDownloadDuration() {
      return mDownloadDuration_;
    }

    public static final int M_HTTPSTATUSCODE_FIELD_NUMBER = 9;
    private int mHttpStatusCode_;
    /**
     * <code>required int32 m_httpStatusCode = 9;</code>
     */
    public boolean hasMHttpStatusCode() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 m_httpStatusCode = 9;</code>
     */
    public int getMHttpStatusCode() {
      return mHttpStatusCode_;
    }

    public static final int M_RELEVANCE_FIELD_NUMBER = 10;
    private long mRelevance_;
    /**
     * <code>required int64 m_relevance = 10;</code>
     */
    public boolean hasMRelevance() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int64 m_relevance = 10;</code>
     */
    public long getMRelevance() {
      return mRelevance_;
    }

    public static final int M_DISTANCEFROMRELEVANTPAGE_FIELD_NUMBER = 11;
    private long mDistanceFromRelevantPage_;
    /**
     * <code>required int64 m_distanceFromRelevantPage = 11;</code>
     */
    public boolean hasMDistanceFromRelevantPage() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required int64 m_distanceFromRelevantPage = 11;</code>
     */
    public long getMDistanceFromRelevantPage() {
      return mDistanceFromRelevantPage_;
    }

    public static final int M_FRESHNESS_FIELD_NUMBER = 12;
    private int mFreshness_;
    /**
     * <code>required int32 m_freshness = 12;</code>
     */
    public boolean hasMFreshness() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required int32 m_freshness = 12;</code>
     */
    public int getMFreshness() {
      return mFreshness_;
    }

    private void initFields() {
      mId_ = 0;
      mLink_ = "";
      mDomain_ = "";
      mAbsolute_ = false;
      mPriority_ = 0;
      mExtractedTime_ = 0L;
      mCrawledTime_ = 0L;
      mDownloadDuration_ = 0L;
      mHttpStatusCode_ = 0;
      mRelevance_ = 0L;
      mDistanceFromRelevantPage_ = 0L;
      mFreshness_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMLink()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMDomain()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMAbsolute()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMPriority()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMExtractedTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMCrawledTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMDownloadDuration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMHttpStatusCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMRelevance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMDistanceFromRelevantPage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMFreshness()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, mId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMLinkBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMDomainBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, mAbsolute_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, mPriority_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, mExtractedTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, mCrawledTime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, mDownloadDuration_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, mHttpStatusCode_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, mRelevance_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, mDistanceFromRelevantPage_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, mFreshness_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMLinkBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMDomainBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, mAbsolute_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, mPriority_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, mExtractedTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, mCrawledTime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, mDownloadDuration_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, mHttpStatusCode_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, mRelevance_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, mDistanceFromRelevantPage_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, mFreshness_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.message.message.URLObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.message.message.URLObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.message.message.URLObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.message.message.URLObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.message.message.URLObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.message.message.URLObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.message.message.URLObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.message.message.URLObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.message.message.URLObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.message.message.URLObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.message.message.URLObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.URLObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.URLObject)
        proto.message.message.URLObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.message.message.internal_static_message_URLObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.message.message.internal_static_message_URLObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.message.message.URLObject.class, proto.message.message.URLObject.Builder.class);
      }

      // Construct using proto.message.message.URLObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        mLink_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        mDomain_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        mAbsolute_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        mPriority_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        mExtractedTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        mCrawledTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        mDownloadDuration_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        mHttpStatusCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        mRelevance_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        mDistanceFromRelevantPage_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        mFreshness_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.message.message.internal_static_message_URLObject_descriptor;
      }

      public proto.message.message.URLObject getDefaultInstanceForType() {
        return proto.message.message.URLObject.getDefaultInstance();
      }

      public proto.message.message.URLObject build() {
        proto.message.message.URLObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.message.message.URLObject buildPartial() {
        proto.message.message.URLObject result = new proto.message.message.URLObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mId_ = mId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mLink_ = mLink_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mDomain_ = mDomain_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mAbsolute_ = mAbsolute_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mPriority_ = mPriority_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.mExtractedTime_ = mExtractedTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.mCrawledTime_ = mCrawledTime_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.mDownloadDuration_ = mDownloadDuration_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.mHttpStatusCode_ = mHttpStatusCode_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.mRelevance_ = mRelevance_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.mDistanceFromRelevantPage_ = mDistanceFromRelevantPage_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.mFreshness_ = mFreshness_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.message.message.URLObject) {
          return mergeFrom((proto.message.message.URLObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.message.message.URLObject other) {
        if (other == proto.message.message.URLObject.getDefaultInstance()) return this;
        if (other.hasMId()) {
          setMId(other.getMId());
        }
        if (other.hasMLink()) {
          bitField0_ |= 0x00000002;
          mLink_ = other.mLink_;
          onChanged();
        }
        if (other.hasMDomain()) {
          bitField0_ |= 0x00000004;
          mDomain_ = other.mDomain_;
          onChanged();
        }
        if (other.hasMAbsolute()) {
          setMAbsolute(other.getMAbsolute());
        }
        if (other.hasMPriority()) {
          setMPriority(other.getMPriority());
        }
        if (other.hasMExtractedTime()) {
          setMExtractedTime(other.getMExtractedTime());
        }
        if (other.hasMCrawledTime()) {
          setMCrawledTime(other.getMCrawledTime());
        }
        if (other.hasMDownloadDuration()) {
          setMDownloadDuration(other.getMDownloadDuration());
        }
        if (other.hasMHttpStatusCode()) {
          setMHttpStatusCode(other.getMHttpStatusCode());
        }
        if (other.hasMRelevance()) {
          setMRelevance(other.getMRelevance());
        }
        if (other.hasMDistanceFromRelevantPage()) {
          setMDistanceFromRelevantPage(other.getMDistanceFromRelevantPage());
        }
        if (other.hasMFreshness()) {
          setMFreshness(other.getMFreshness());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMId()) {
          
          return false;
        }
        if (!hasMLink()) {
          
          return false;
        }
        if (!hasMDomain()) {
          
          return false;
        }
        if (!hasMAbsolute()) {
          
          return false;
        }
        if (!hasMPriority()) {
          
          return false;
        }
        if (!hasMExtractedTime()) {
          
          return false;
        }
        if (!hasMCrawledTime()) {
          
          return false;
        }
        if (!hasMDownloadDuration()) {
          
          return false;
        }
        if (!hasMHttpStatusCode()) {
          
          return false;
        }
        if (!hasMRelevance()) {
          
          return false;
        }
        if (!hasMDistanceFromRelevantPage()) {
          
          return false;
        }
        if (!hasMFreshness()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.message.message.URLObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.message.message.URLObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int mId_ ;
      /**
       * <code>required int32 m_id = 1;</code>
       */
      public boolean hasMId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 m_id = 1;</code>
       */
      public int getMId() {
        return mId_;
      }
      /**
       * <code>required int32 m_id = 1;</code>
       */
      public Builder setMId(int value) {
        bitField0_ |= 0x00000001;
        mId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 m_id = 1;</code>
       */
      public Builder clearMId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mLink_ = "";
      /**
       * <code>required string m_link = 2;</code>
       */
      public boolean hasMLink() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string m_link = 2;</code>
       */
      public java.lang.String getMLink() {
        java.lang.Object ref = mLink_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mLink_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string m_link = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMLinkBytes() {
        java.lang.Object ref = mLink_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mLink_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string m_link = 2;</code>
       */
      public Builder setMLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mLink_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string m_link = 2;</code>
       */
      public Builder clearMLink() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mLink_ = getDefaultInstance().getMLink();
        onChanged();
        return this;
      }
      /**
       * <code>required string m_link = 2;</code>
       */
      public Builder setMLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mLink_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mDomain_ = "";
      /**
       * <code>required string m_domain = 3;</code>
       */
      public boolean hasMDomain() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string m_domain = 3;</code>
       */
      public java.lang.String getMDomain() {
        java.lang.Object ref = mDomain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mDomain_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string m_domain = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMDomainBytes() {
        java.lang.Object ref = mDomain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mDomain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string m_domain = 3;</code>
       */
      public Builder setMDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mDomain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string m_domain = 3;</code>
       */
      public Builder clearMDomain() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mDomain_ = getDefaultInstance().getMDomain();
        onChanged();
        return this;
      }
      /**
       * <code>required string m_domain = 3;</code>
       */
      public Builder setMDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mDomain_ = value;
        onChanged();
        return this;
      }

      private boolean mAbsolute_ ;
      /**
       * <code>required bool m_absolute = 4;</code>
       */
      public boolean hasMAbsolute() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool m_absolute = 4;</code>
       */
      public boolean getMAbsolute() {
        return mAbsolute_;
      }
      /**
       * <code>required bool m_absolute = 4;</code>
       */
      public Builder setMAbsolute(boolean value) {
        bitField0_ |= 0x00000008;
        mAbsolute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool m_absolute = 4;</code>
       */
      public Builder clearMAbsolute() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mAbsolute_ = false;
        onChanged();
        return this;
      }

      private int mPriority_ ;
      /**
       * <code>required int32 m_priority = 5;</code>
       */
      public boolean hasMPriority() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 m_priority = 5;</code>
       */
      public int getMPriority() {
        return mPriority_;
      }
      /**
       * <code>required int32 m_priority = 5;</code>
       */
      public Builder setMPriority(int value) {
        bitField0_ |= 0x00000010;
        mPriority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 m_priority = 5;</code>
       */
      public Builder clearMPriority() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mPriority_ = 0;
        onChanged();
        return this;
      }

      private long mExtractedTime_ ;
      /**
       * <code>required int64 m_extractedTime = 6;</code>
       */
      public boolean hasMExtractedTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 m_extractedTime = 6;</code>
       */
      public long getMExtractedTime() {
        return mExtractedTime_;
      }
      /**
       * <code>required int64 m_extractedTime = 6;</code>
       */
      public Builder setMExtractedTime(long value) {
        bitField0_ |= 0x00000020;
        mExtractedTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 m_extractedTime = 6;</code>
       */
      public Builder clearMExtractedTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        mExtractedTime_ = 0L;
        onChanged();
        return this;
      }

      private long mCrawledTime_ ;
      /**
       * <code>required int64 m_crawledTime = 7;</code>
       */
      public boolean hasMCrawledTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int64 m_crawledTime = 7;</code>
       */
      public long getMCrawledTime() {
        return mCrawledTime_;
      }
      /**
       * <code>required int64 m_crawledTime = 7;</code>
       */
      public Builder setMCrawledTime(long value) {
        bitField0_ |= 0x00000040;
        mCrawledTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 m_crawledTime = 7;</code>
       */
      public Builder clearMCrawledTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        mCrawledTime_ = 0L;
        onChanged();
        return this;
      }

      private long mDownloadDuration_ ;
      /**
       * <code>required int64 m_downloadDuration = 8;</code>
       */
      public boolean hasMDownloadDuration() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int64 m_downloadDuration = 8;</code>
       */
      public long getMDownloadDuration() {
        return mDownloadDuration_;
      }
      /**
       * <code>required int64 m_downloadDuration = 8;</code>
       */
      public Builder setMDownloadDuration(long value) {
        bitField0_ |= 0x00000080;
        mDownloadDuration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 m_downloadDuration = 8;</code>
       */
      public Builder clearMDownloadDuration() {
        bitField0_ = (bitField0_ & ~0x00000080);
        mDownloadDuration_ = 0L;
        onChanged();
        return this;
      }

      private int mHttpStatusCode_ ;
      /**
       * <code>required int32 m_httpStatusCode = 9;</code>
       */
      public boolean hasMHttpStatusCode() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 m_httpStatusCode = 9;</code>
       */
      public int getMHttpStatusCode() {
        return mHttpStatusCode_;
      }
      /**
       * <code>required int32 m_httpStatusCode = 9;</code>
       */
      public Builder setMHttpStatusCode(int value) {
        bitField0_ |= 0x00000100;
        mHttpStatusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 m_httpStatusCode = 9;</code>
       */
      public Builder clearMHttpStatusCode() {
        bitField0_ = (bitField0_ & ~0x00000100);
        mHttpStatusCode_ = 0;
        onChanged();
        return this;
      }

      private long mRelevance_ ;
      /**
       * <code>required int64 m_relevance = 10;</code>
       */
      public boolean hasMRelevance() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int64 m_relevance = 10;</code>
       */
      public long getMRelevance() {
        return mRelevance_;
      }
      /**
       * <code>required int64 m_relevance = 10;</code>
       */
      public Builder setMRelevance(long value) {
        bitField0_ |= 0x00000200;
        mRelevance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 m_relevance = 10;</code>
       */
      public Builder clearMRelevance() {
        bitField0_ = (bitField0_ & ~0x00000200);
        mRelevance_ = 0L;
        onChanged();
        return this;
      }

      private long mDistanceFromRelevantPage_ ;
      /**
       * <code>required int64 m_distanceFromRelevantPage = 11;</code>
       */
      public boolean hasMDistanceFromRelevantPage() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required int64 m_distanceFromRelevantPage = 11;</code>
       */
      public long getMDistanceFromRelevantPage() {
        return mDistanceFromRelevantPage_;
      }
      /**
       * <code>required int64 m_distanceFromRelevantPage = 11;</code>
       */
      public Builder setMDistanceFromRelevantPage(long value) {
        bitField0_ |= 0x00000400;
        mDistanceFromRelevantPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 m_distanceFromRelevantPage = 11;</code>
       */
      public Builder clearMDistanceFromRelevantPage() {
        bitField0_ = (bitField0_ & ~0x00000400);
        mDistanceFromRelevantPage_ = 0L;
        onChanged();
        return this;
      }

      private int mFreshness_ ;
      /**
       * <code>required int32 m_freshness = 12;</code>
       */
      public boolean hasMFreshness() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required int32 m_freshness = 12;</code>
       */
      public int getMFreshness() {
        return mFreshness_;
      }
      /**
       * <code>required int32 m_freshness = 12;</code>
       */
      public Builder setMFreshness(int value) {
        bitField0_ |= 0x00000800;
        mFreshness_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 m_freshness = 12;</code>
       */
      public Builder clearMFreshness() {
        bitField0_ = (bitField0_ & ~0x00000800);
        mFreshness_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:message.URLObject)
    }

    static {
      defaultInstance = new URLObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:message.URLObject)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_URLObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_URLObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\007message\"\227\002\n\tURLObject\022\014" +
      "\n\004m_id\030\001 \002(\005\022\016\n\006m_link\030\002 \002(\t\022\020\n\010m_domain" +
      "\030\003 \002(\t\022\022\n\nm_absolute\030\004 \002(\010\022\022\n\nm_priority" +
      "\030\005 \002(\005\022\027\n\017m_extractedTime\030\006 \002(\003\022\025\n\rm_cra" +
      "wledTime\030\007 \002(\003\022\032\n\022m_downloadDuration\030\010 \002" +
      "(\003\022\030\n\020m_httpStatusCode\030\t \002(\005\022\023\n\013m_releva" +
      "nce\030\n \002(\003\022\"\n\032m_distanceFromRelevantPage\030" +
      "\013 \002(\003\022\023\n\013m_freshness\030\014 \002(\005B\030\n\rproto.mess" +
      "ageB\007message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_URLObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_URLObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_message_URLObject_descriptor,
        new java.lang.String[] { "MId", "MLink", "MDomain", "MAbsolute", "MPriority", "MExtractedTime", "MCrawledTime", "MDownloadDuration", "MHttpStatusCode", "MRelevance", "MDistanceFromRelevantPage", "MFreshness", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
