// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package proto.message;

public final class message {
  private message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface URLmessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.URLmessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string link = 2;</code>
     */
    boolean hasLink();
    /**
     * <code>required string link = 2;</code>
     */
    java.lang.String getLink();
    /**
     * <code>required string link = 2;</code>
     */
    com.google.protobuf.ByteString
        getLinkBytes();

    /**
     * <code>optional string domain = 3;</code>
     */
    boolean hasDomain();
    /**
     * <code>optional string domain = 3;</code>
     */
    java.lang.String getDomain();
    /**
     * <code>optional string domain = 3;</code>
     */
    com.google.protobuf.ByteString
        getDomainBytes();

    /**
     * <code>optional bool absolute = 4;</code>
     */
    boolean hasAbsolute();
    /**
     * <code>optional bool absolute = 4;</code>
     */
    boolean getAbsolute();

    /**
     * <code>optional int32 priority = 5;</code>
     */
    boolean hasPriority();
    /**
     * <code>optional int32 priority = 5;</code>
     */
    int getPriority();

    /**
     * <code>optional int64 extracted_time = 6;</code>
     */
    boolean hasExtractedTime();
    /**
     * <code>optional int64 extracted_time = 6;</code>
     */
    long getExtractedTime();

    /**
     * <code>optional int64 crawled_time = 7;</code>
     */
    boolean hasCrawledTime();
    /**
     * <code>optional int64 crawled_time = 7;</code>
     */
    long getCrawledTime();

    /**
     * <code>optional int64 download_duration = 8;</code>
     */
    boolean hasDownloadDuration();
    /**
     * <code>optional int64 download_duration = 8;</code>
     */
    long getDownloadDuration();

    /**
     * <code>optional int32 http_status_code = 9;</code>
     */
    boolean hasHttpStatusCode();
    /**
     * <code>optional int32 http_status_code = 9;</code>
     */
    int getHttpStatusCode();

    /**
     * <code>optional int64 relevance = 10;</code>
     */
    boolean hasRelevance();
    /**
     * <code>optional int64 relevance = 10;</code>
     */
    long getRelevance();

    /**
     * <code>optional int64 distance_from_relevant_page = 11;</code>
     */
    boolean hasDistanceFromRelevantPage();
    /**
     * <code>optional int64 distance_from_relevant_page = 11;</code>
     */
    long getDistanceFromRelevantPage();

    /**
     * <code>optional int32 freshness = 12;</code>
     */
    boolean hasFreshness();
    /**
     * <code>optional int32 freshness = 12;</code>
     */
    int getFreshness();
  }
  /**
   * Protobuf type {@code message.URLmessage}
   */
  public static final class URLmessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:message.URLmessage)
      URLmessageOrBuilder {
    // Use URLmessage.newBuilder() to construct.
    private URLmessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private URLmessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final URLmessage defaultInstance;
    public static URLmessage getDefaultInstance() {
      return defaultInstance;
    }

    public URLmessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private URLmessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              link_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              domain_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              absolute_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              priority_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              extractedTime_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              crawledTime_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              downloadDuration_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              httpStatusCode_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              relevance_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              distanceFromRelevantPage_ = input.readInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              freshness_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.message.message.internal_static_message_URLmessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.message.message.internal_static_message_URLmessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.message.message.URLmessage.class, proto.message.message.URLmessage.Builder.class);
    }

    public static com.google.protobuf.Parser<URLmessage> PARSER =
        new com.google.protobuf.AbstractParser<URLmessage>() {
      public URLmessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new URLmessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<URLmessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int LINK_FIELD_NUMBER = 2;
    private java.lang.Object link_;
    /**
     * <code>required string link = 2;</code>
     */
    public boolean hasLink() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string link = 2;</code>
     */
    public java.lang.String getLink() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          link_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string link = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOMAIN_FIELD_NUMBER = 3;
    private java.lang.Object domain_;
    /**
     * <code>optional string domain = 3;</code>
     */
    public boolean hasDomain() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string domain = 3;</code>
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          domain_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string domain = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ABSOLUTE_FIELD_NUMBER = 4;
    private boolean absolute_;
    /**
     * <code>optional bool absolute = 4;</code>
     */
    public boolean hasAbsolute() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool absolute = 4;</code>
     */
    public boolean getAbsolute() {
      return absolute_;
    }

    public static final int PRIORITY_FIELD_NUMBER = 5;
    private int priority_;
    /**
     * <code>optional int32 priority = 5;</code>
     */
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 priority = 5;</code>
     */
    public int getPriority() {
      return priority_;
    }

    public static final int EXTRACTED_TIME_FIELD_NUMBER = 6;
    private long extractedTime_;
    /**
     * <code>optional int64 extracted_time = 6;</code>
     */
    public boolean hasExtractedTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 extracted_time = 6;</code>
     */
    public long getExtractedTime() {
      return extractedTime_;
    }

    public static final int CRAWLED_TIME_FIELD_NUMBER = 7;
    private long crawledTime_;
    /**
     * <code>optional int64 crawled_time = 7;</code>
     */
    public boolean hasCrawledTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 crawled_time = 7;</code>
     */
    public long getCrawledTime() {
      return crawledTime_;
    }

    public static final int DOWNLOAD_DURATION_FIELD_NUMBER = 8;
    private long downloadDuration_;
    /**
     * <code>optional int64 download_duration = 8;</code>
     */
    public boolean hasDownloadDuration() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 download_duration = 8;</code>
     */
    public long getDownloadDuration() {
      return downloadDuration_;
    }

    public static final int HTTP_STATUS_CODE_FIELD_NUMBER = 9;
    private int httpStatusCode_;
    /**
     * <code>optional int32 http_status_code = 9;</code>
     */
    public boolean hasHttpStatusCode() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 http_status_code = 9;</code>
     */
    public int getHttpStatusCode() {
      return httpStatusCode_;
    }

    public static final int RELEVANCE_FIELD_NUMBER = 10;
    private long relevance_;
    /**
     * <code>optional int64 relevance = 10;</code>
     */
    public boolean hasRelevance() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 relevance = 10;</code>
     */
    public long getRelevance() {
      return relevance_;
    }

    public static final int DISTANCE_FROM_RELEVANT_PAGE_FIELD_NUMBER = 11;
    private long distanceFromRelevantPage_;
    /**
     * <code>optional int64 distance_from_relevant_page = 11;</code>
     */
    public boolean hasDistanceFromRelevantPage() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int64 distance_from_relevant_page = 11;</code>
     */
    public long getDistanceFromRelevantPage() {
      return distanceFromRelevantPage_;
    }

    public static final int FRESHNESS_FIELD_NUMBER = 12;
    private int freshness_;
    /**
     * <code>optional int32 freshness = 12;</code>
     */
    public boolean hasFreshness() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 freshness = 12;</code>
     */
    public int getFreshness() {
      return freshness_;
    }

    private void initFields() {
      id_ = 0;
      link_ = "";
      domain_ = "";
      absolute_ = false;
      priority_ = 0;
      extractedTime_ = 0L;
      crawledTime_ = 0L;
      downloadDuration_ = 0L;
      httpStatusCode_ = 0;
      relevance_ = 0L;
      distanceFromRelevantPage_ = 0L;
      freshness_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLink()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLinkBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDomainBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, absolute_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, priority_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, extractedTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, crawledTime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, downloadDuration_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, httpStatusCode_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, relevance_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, distanceFromRelevantPage_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, freshness_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLinkBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDomainBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, absolute_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, priority_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, extractedTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, crawledTime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, downloadDuration_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, httpStatusCode_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, relevance_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, distanceFromRelevantPage_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, freshness_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.message.message.URLmessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.message.message.URLmessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.message.message.URLmessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.message.message.URLmessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.message.message.URLmessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.message.message.URLmessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.message.message.URLmessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.message.message.URLmessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.message.message.URLmessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.message.message.URLmessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.message.message.URLmessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.URLmessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.URLmessage)
        proto.message.message.URLmessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.message.message.internal_static_message_URLmessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.message.message.internal_static_message_URLmessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.message.message.URLmessage.class, proto.message.message.URLmessage.Builder.class);
      }

      // Construct using proto.message.message.URLmessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        link_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        domain_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        absolute_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        priority_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        extractedTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        crawledTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        downloadDuration_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        httpStatusCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        relevance_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        distanceFromRelevantPage_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        freshness_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.message.message.internal_static_message_URLmessage_descriptor;
      }

      public proto.message.message.URLmessage getDefaultInstanceForType() {
        return proto.message.message.URLmessage.getDefaultInstance();
      }

      public proto.message.message.URLmessage build() {
        proto.message.message.URLmessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.message.message.URLmessage buildPartial() {
        proto.message.message.URLmessage result = new proto.message.message.URLmessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.link_ = link_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.domain_ = domain_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.absolute_ = absolute_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.priority_ = priority_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.extractedTime_ = extractedTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.crawledTime_ = crawledTime_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.downloadDuration_ = downloadDuration_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.httpStatusCode_ = httpStatusCode_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.relevance_ = relevance_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.distanceFromRelevantPage_ = distanceFromRelevantPage_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.freshness_ = freshness_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.message.message.URLmessage) {
          return mergeFrom((proto.message.message.URLmessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.message.message.URLmessage other) {
        if (other == proto.message.message.URLmessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLink()) {
          bitField0_ |= 0x00000002;
          link_ = other.link_;
          onChanged();
        }
        if (other.hasDomain()) {
          bitField0_ |= 0x00000004;
          domain_ = other.domain_;
          onChanged();
        }
        if (other.hasAbsolute()) {
          setAbsolute(other.getAbsolute());
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        if (other.hasExtractedTime()) {
          setExtractedTime(other.getExtractedTime());
        }
        if (other.hasCrawledTime()) {
          setCrawledTime(other.getCrawledTime());
        }
        if (other.hasDownloadDuration()) {
          setDownloadDuration(other.getDownloadDuration());
        }
        if (other.hasHttpStatusCode()) {
          setHttpStatusCode(other.getHttpStatusCode());
        }
        if (other.hasRelevance()) {
          setRelevance(other.getRelevance());
        }
        if (other.hasDistanceFromRelevantPage()) {
          setDistanceFromRelevantPage(other.getDistanceFromRelevantPage());
        }
        if (other.hasFreshness()) {
          setFreshness(other.getFreshness());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasLink()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.message.message.URLmessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.message.message.URLmessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object link_ = "";
      /**
       * <code>required string link = 2;</code>
       */
      public boolean hasLink() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string link = 2;</code>
       */
      public java.lang.String getLink() {
        java.lang.Object ref = link_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            link_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string link = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLinkBytes() {
        java.lang.Object ref = link_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          link_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string link = 2;</code>
       */
      public Builder setLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        link_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string link = 2;</code>
       */
      public Builder clearLink() {
        bitField0_ = (bitField0_ & ~0x00000002);
        link_ = getDefaultInstance().getLink();
        onChanged();
        return this;
      }
      /**
       * <code>required string link = 2;</code>
       */
      public Builder setLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        link_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object domain_ = "";
      /**
       * <code>optional string domain = 3;</code>
       */
      public boolean hasDomain() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string domain = 3;</code>
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            domain_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string domain = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string domain = 3;</code>
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string domain = 3;</code>
       */
      public Builder clearDomain() {
        bitField0_ = (bitField0_ & ~0x00000004);
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <code>optional string domain = 3;</code>
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        domain_ = value;
        onChanged();
        return this;
      }

      private boolean absolute_ ;
      /**
       * <code>optional bool absolute = 4;</code>
       */
      public boolean hasAbsolute() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool absolute = 4;</code>
       */
      public boolean getAbsolute() {
        return absolute_;
      }
      /**
       * <code>optional bool absolute = 4;</code>
       */
      public Builder setAbsolute(boolean value) {
        bitField0_ |= 0x00000008;
        absolute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool absolute = 4;</code>
       */
      public Builder clearAbsolute() {
        bitField0_ = (bitField0_ & ~0x00000008);
        absolute_ = false;
        onChanged();
        return this;
      }

      private int priority_ ;
      /**
       * <code>optional int32 priority = 5;</code>
       */
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 priority = 5;</code>
       */
      public int getPriority() {
        return priority_;
      }
      /**
       * <code>optional int32 priority = 5;</code>
       */
      public Builder setPriority(int value) {
        bitField0_ |= 0x00000010;
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 priority = 5;</code>
       */
      public Builder clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000010);
        priority_ = 0;
        onChanged();
        return this;
      }

      private long extractedTime_ ;
      /**
       * <code>optional int64 extracted_time = 6;</code>
       */
      public boolean hasExtractedTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 extracted_time = 6;</code>
       */
      public long getExtractedTime() {
        return extractedTime_;
      }
      /**
       * <code>optional int64 extracted_time = 6;</code>
       */
      public Builder setExtractedTime(long value) {
        bitField0_ |= 0x00000020;
        extractedTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 extracted_time = 6;</code>
       */
      public Builder clearExtractedTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        extractedTime_ = 0L;
        onChanged();
        return this;
      }

      private long crawledTime_ ;
      /**
       * <code>optional int64 crawled_time = 7;</code>
       */
      public boolean hasCrawledTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 crawled_time = 7;</code>
       */
      public long getCrawledTime() {
        return crawledTime_;
      }
      /**
       * <code>optional int64 crawled_time = 7;</code>
       */
      public Builder setCrawledTime(long value) {
        bitField0_ |= 0x00000040;
        crawledTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 crawled_time = 7;</code>
       */
      public Builder clearCrawledTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        crawledTime_ = 0L;
        onChanged();
        return this;
      }

      private long downloadDuration_ ;
      /**
       * <code>optional int64 download_duration = 8;</code>
       */
      public boolean hasDownloadDuration() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 download_duration = 8;</code>
       */
      public long getDownloadDuration() {
        return downloadDuration_;
      }
      /**
       * <code>optional int64 download_duration = 8;</code>
       */
      public Builder setDownloadDuration(long value) {
        bitField0_ |= 0x00000080;
        downloadDuration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 download_duration = 8;</code>
       */
      public Builder clearDownloadDuration() {
        bitField0_ = (bitField0_ & ~0x00000080);
        downloadDuration_ = 0L;
        onChanged();
        return this;
      }

      private int httpStatusCode_ ;
      /**
       * <code>optional int32 http_status_code = 9;</code>
       */
      public boolean hasHttpStatusCode() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 http_status_code = 9;</code>
       */
      public int getHttpStatusCode() {
        return httpStatusCode_;
      }
      /**
       * <code>optional int32 http_status_code = 9;</code>
       */
      public Builder setHttpStatusCode(int value) {
        bitField0_ |= 0x00000100;
        httpStatusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 http_status_code = 9;</code>
       */
      public Builder clearHttpStatusCode() {
        bitField0_ = (bitField0_ & ~0x00000100);
        httpStatusCode_ = 0;
        onChanged();
        return this;
      }

      private long relevance_ ;
      /**
       * <code>optional int64 relevance = 10;</code>
       */
      public boolean hasRelevance() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 relevance = 10;</code>
       */
      public long getRelevance() {
        return relevance_;
      }
      /**
       * <code>optional int64 relevance = 10;</code>
       */
      public Builder setRelevance(long value) {
        bitField0_ |= 0x00000200;
        relevance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 relevance = 10;</code>
       */
      public Builder clearRelevance() {
        bitField0_ = (bitField0_ & ~0x00000200);
        relevance_ = 0L;
        onChanged();
        return this;
      }

      private long distanceFromRelevantPage_ ;
      /**
       * <code>optional int64 distance_from_relevant_page = 11;</code>
       */
      public boolean hasDistanceFromRelevantPage() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int64 distance_from_relevant_page = 11;</code>
       */
      public long getDistanceFromRelevantPage() {
        return distanceFromRelevantPage_;
      }
      /**
       * <code>optional int64 distance_from_relevant_page = 11;</code>
       */
      public Builder setDistanceFromRelevantPage(long value) {
        bitField0_ |= 0x00000400;
        distanceFromRelevantPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 distance_from_relevant_page = 11;</code>
       */
      public Builder clearDistanceFromRelevantPage() {
        bitField0_ = (bitField0_ & ~0x00000400);
        distanceFromRelevantPage_ = 0L;
        onChanged();
        return this;
      }

      private int freshness_ ;
      /**
       * <code>optional int32 freshness = 12;</code>
       */
      public boolean hasFreshness() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 freshness = 12;</code>
       */
      public int getFreshness() {
        return freshness_;
      }
      /**
       * <code>optional int32 freshness = 12;</code>
       */
      public Builder setFreshness(int value) {
        bitField0_ |= 0x00000800;
        freshness_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 freshness = 12;</code>
       */
      public Builder clearFreshness() {
        bitField0_ = (bitField0_ & ~0x00000800);
        freshness_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:message.URLmessage)
    }

    static {
      defaultInstance = new URLmessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:message.URLmessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_URLmessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_URLmessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\007message\"\210\002\n\nURLmessage\022" +
      "\n\n\002id\030\001 \002(\005\022\014\n\004link\030\002 \002(\t\022\016\n\006domain\030\003 \001(" +
      "\t\022\020\n\010absolute\030\004 \001(\010\022\020\n\010priority\030\005 \001(\005\022\026\n" +
      "\016extracted_time\030\006 \001(\003\022\024\n\014crawled_time\030\007 " +
      "\001(\003\022\031\n\021download_duration\030\010 \001(\003\022\030\n\020http_s" +
      "tatus_code\030\t \001(\005\022\021\n\trelevance\030\n \001(\003\022#\n\033d" +
      "istance_from_relevant_page\030\013 \001(\003\022\021\n\tfres" +
      "hness\030\014 \001(\005B\030\n\rproto.messageB\007message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_URLmessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_URLmessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_message_URLmessage_descriptor,
        new java.lang.String[] { "Id", "Link", "Domain", "Absolute", "Priority", "ExtractedTime", "CrawledTime", "DownloadDuration", "HttpStatusCode", "Relevance", "DistanceFromRelevantPage", "Freshness", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
